name: Online Competition

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  online-competition:
    if: ${{ github.repository != 'utiasDSL/lsy_drone_racing' }}
    runs-on: ubuntu-latest
    env:
      KAGGLE_USERNAME: ${{ secrets.KaggleUsername }}
      KAGGLE_KEY: ${{ secrets.KaggleKey }}

    steps:
      - uses: actions/checkout@v4

      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '2.1.0-0'
          environment-name: test-env
          init-shell: bash
          create-args: python=3.12
          cache-environment: true

      # ⬇️ Acados klonen & bauen
      - name: Clone and build acados
        run: |
          git clone --recursive https://github.com/acados/acados.git
          cd acados
          mkdir build
          cd build
          cmake ..
          make -j2
        shell: micromamba-shell {0}

      # ⬇️ acados_template installieren
      - name: Install acados_template module
        run: |
          cd acados/interfaces/acados_template
          pip install .
        shell: micromamba-shell {0}

      # ⬇️ dein Projekt installieren
      - name: Install project
        run: pip install .[online_submission,test]
        shell: micromamba-shell {0}

      - name: Run simulation tests
        run: python scripts/kaggle.py
        shell: micromamba-shell {0}

      - name: Export with kaggle
        run: kaggle competitions submit -c lsy-drone-racing-ss-25 -f submission.csv -m "Automated submission"
        shell: micromamba-shell {0}
