name: Online Competition

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  online-competition:
    if: ${{ github.repository != 'utiasDSL/lsy_drone_racing' }}
    runs-on: ubuntu-latest
    env:
      KAGGLE_USERNAME: ${{ secrets.KaggleUsername }}
      KAGGLE_KEY: ${{ secrets.KaggleKey }}
      ACADOS_TERA_PATH: /home/runner/bin/t_renderer

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '2.1.0-0'
          environment-name: test-env
          init-shell: bash
          create-args: python=3.12
          cache-environment: true

      - name: Install system packages for acados
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential

      - name: Clone and build acados
        run: |
          git clone --recursive https://github.com/acados/acados.git
          cd acados
          mkdir build
          cd build
          cmake ..
          make -j2
        shell: micromamba-shell {0}

      - name: Install acados_template module
        run: |
          cd acados/interfaces/acados_template
          pip install .
        shell: micromamba-shell {0}

      - name: Install your project dependencies
        run: pip install .[online_submission,test]
        shell: micromamba-shell {0}

      - name: Download Tera renderer
        run: |
          mkdir -p /home/runner/bin
          curl -L https://github.com/acados/tera_renderer/releases/download/v0.0.34/t_renderer-v0.0.34-linux -o /home/runner/bin/t_renderer
          chmod +x /home/runner/bin/t_renderer

      - name: Run simulation tests
        run: python scripts/kaggle.py
        shell: micromamba-shell {0}

      - name: Export with kaggle
        run: kaggle competitions submit -c lsy-drone-racing-ss-25 -f submission.csv -m "Automated submission"
        shell: micromamba-shell {0}
