name: Online Competition

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  online-competition:
    if: ${{ github.repository != 'utiasDSL/lsy_drone_racing' }}
    runs-on: ubuntu-latest
    env:
      KAGGLE_USERNAME: ${{ secrets.KaggleUsername }}
      KAGGLE_KEY: ${{ secrets.KaggleKey }}
      ACADOS_SOURCE_DIR: ${{ github.workspace }}/acados

    steps:
      - uses: actions/checkout@v4

      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '2.1.0-0'
          environment-name: test-env
          init-shell: bash
          create-args: python=3.12
          cache-environment: true

      - name: Install Python dependencies
        run: pip install .[online_submission,test]
        shell: micromamba-shell {0}

      - name: Install acados_template module
        run: |
          cd acados/interfaces/acados_template
          pip install .
        shell: micromamba-shell {0}

      - name: Install tera template renderer
        run: |
          mkdir -p $ACADOS_SOURCE_DIR/bin
          curl -L https://github.com/acados/tera_renderer/releases/download/v0.0.34/t_renderer-v0.0.34-linux -o $ACADOS_SOURCE_DIR/bin/t_renderer
          chmod +x $ACADOS_SOURCE_DIR/bin/t_renderer
        shell: micromamba-shell {0}

      - name: Run simulation tests
        run: python scripts/kaggle.py
        shell: micromamba-shell {0}

      - name: Export with kaggle
        run: kaggle competitions submit -c lsy-drone-racing-ss-25 -f submission.csv -m "Automated submission"
        shell: micromamba-shell {0}
