name: Online Competition

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  online-competition:
    if: ${{ github.repository != 'utiasDSL/lsy_drone_racing' }}
    runs-on: ubuntu-latest
    env:
      KAGGLE_USERNAME: ${{ secrets.KaggleUsername }}
      KAGGLE_KEY: ${{ secrets.KaggleKey }}
      ACADOS_SOURCE_DIR: ${{ github.workspace }}/acados  # wichtig für acados_template!

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up micromamba environment
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '2.1.0-0'
          environment-name: test-env
          init-shell: bash
          create-args: python=3.12
          cache-environment: true

      - name: Install Python dependencies
        run: pip install .[online_submission,test]
        shell: micromamba-shell {0}

      - name: Build acados C libraries
        run: |
          cd acados
          mkdir -p build
          cd build
          cmake .. -DACADOS_WITH_QPOASES=ON -DCMAKE_BUILD_TYPE=Release
          make -j2
        shell: micromamba-shell {0}

      - name: Install acados_template
        run: pip install ./acados/interfaces/acados_template
        shell: micromamba-shell {0}

      - name: Run simulation tests
        run: python scripts/kaggle.py
        shell: micromamba-shell {0}

      - name: Export to Kaggle
        run: kaggle competitions submit -c lsy-drone-racing-ss-25 -f submission.csv -m "Automated submission"
        shell: micromamba-shell {0}
